services:
  php:
    container_name: "dootask-php"
    image: "kuaifan/php:swoole-8.0.rc21"
    shm_size: 2G
    ulimits:
      core:
        soft: 0
        hard: 0
    volumes:
      - ./data:/usr/share/dootask
      - ./docker/crontab/crontab.conf:/etc/supervisor/conf.d/crontab.conf
      - ./docker/php/php.conf:/etc/supervisor/conf.d/php.conf
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/logs/supervisor:/var/log/supervisor
      - ./:/var/www
    environment:
      LANG: "C.UTF-8"
      MODE: "production"
    restart: unless-stopped

  nginx:
    container_name: "dootask-nginx"
    image: "nginx:1.29-alpine"
    ports:
      - "${APP_PORT}:80"
      - "${APP_SSL_PORT:-0}:443"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www
    restart: unless-stopped
